### ISSUE TITLE
Could not resolve import "@polymer/iron-demo-helpers/demo-pages-shared-styles.js" in "demo\demo.js"

### ISSUE THREAD

**Issue by daliboris** [Jinntec/Fore#191]
I tried to run demo of the Fore repository.

I followed steps in the Readme (clonning, `npm i`, `npm run start` ).

The demo pages are displayed, but the _Fore_ content is missing, I only see static text.

![vivaldi_2023-01-27T09-59-44](https://user-images.githubusercontent.com/8056045/215047953-9da9efa1-2284-403d-bf2e-d6ab4693b39f.png)

There is error log in the console:

```text
  Error: Could not resolve import "@polymer/iron-demo-helpers/demo-pages-shared-styles.js" in "demo\demo.js".
      at Object.resolveImport (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\plugins\nodeResolvePlugin.js:81:23)
      at async resolveImport (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\plugins\resolveModuleImportsPlugin.js:132:30)
      at async maybeResolveImport (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\plugins\resolveModuleImportsPlugin.js:82:41)
      at async resolveModuleImports (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\plugins\resolveModuleImportsPlugin.js:101:36)       
      at async Object.transform (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\plugins\resolveModuleImportsPlugin.js:149:49)
      at async pluginTransformMiddleware (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\middleware\plugin-transform.js:77:34)
      at async watchServedFilesMiddleware (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\middleware\watch-served-files.js:18:9)        
      at async messageChannelMiddleware (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\middleware\message-channel.js:37:9)
      at async etagCacheMiddleware (V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\middleware\etag-cache.js:9:9)
      at async V:\Projekty\Github\Daliboris\Fore\node_modules\es-dev-server\dist\create-middlewares.js:105:9

```

I use Windows 10, node v16.13.0, npm 8.6.0, Visua Studio Code 1.7.43.

What other steps should I take? Thanks for any hints.

**Comment by JoernT** [comment]
i assume you checked out the 'dev' branch?

**Comment by daliboris** [comment]
Yes, you are right. I made fork of the dev branch (https://github.com/daliboris/Fore).

**Comment by JoernT** [comment]
hm, that's really strange - the above dependency is defined in demo/package.json - could you check if you got a 'node_modules' folder in your demo directory please?

**Comment by daliboris** [comment]
Thank you for the hint. There was not `demo/node_modules` directory. I had to run `npm i` inside `demo` folder, not only in main Fore directory.

Now it works. Thank you again.

**Comment by JoernT** [comment]
you're welcome
