### ISSUE TITLE
build broken in demo branch

### ISSUE THREAD

**Issue by pherk** [Jinntec/Fore#62]
running 'git checkout demo -- & npm run build'
building fore.js and fore-all.js succeeds
but ...
./demo/demo.js → dist/fore-demo.js...
[!] Error: Could not resolve '../dist/fore-demo.js' from demo/demo.js
Error: Could not resolve '../dist/fore-demo.js' from demo/demo.js
    at error (/home/peter/devel/Fore-0.25.1/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/home/peter/devel/Fore-0.25.1/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (/home/peter/devel/Fore-0.25.1/node_modules/rollup/dist/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/peter/devel/Fore-0.25.1/node_modules/rollup/dist/shared/node-entry.js:38:28)

Ubuntu 20.04, node 15, firefox 92

**Comment by JoernT** [comment]
thanks for reporting - will look into it. Guess i've forgotten to merge some change from dev branch

**Comment by JoernT** [comment]
should be fixed now

**Comment by pherk** [comment]
@polymer does not exist

./demo/demo-build.js → dist/fore-demo.js...
[!] Error: Could not resolve './node_modules/@polymer/iron-demo-helpers/demo-snippet.js' from demo/demo-build.js
Error: Could not resolve './node_modules/@polymer/iron-demo-helpers/demo-snippet.js' from demo/demo-build.js
    at error (/home/peter/devel/Fore-0.25.1/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/home/peter/devel/Fore-0.25.1/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (/home/peter/devel/Fore-0.25.1/node_modules/rollup/disot/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/peter/devel/Fore-0.25.1/node_modules/rollup/dist/shared/node-entry.js:38:28)

**Comment by JoernT** [comment]
arg- works in local workspace but not on CI run on github. Probably i'll just disable git workflow for demo branch

**Comment by JoernT** [comment]
merged demo deps into root package.json. This now runs green again.
